# Generated by Django 3.0.3 on 2020-02-20 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_auto_20200220_2031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tool',
            old_name='typeof',
            new_name='name',
        ),
    ]
