# Generated by Django 3.0.3 on 2020-02-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_auto_20200220_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='owner',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
