# Generated by Django 3.0.3 on 2020-02-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_tool_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='photo',
            field=models.URLField(null=True),
        ),
    ]
